### ISSUE TITLE
Folder /dist missing (as well as the index.js)

### ISSUE THREAD

**Issue by zefirzdravkov** [SamVerschueren/map-age-cleaner#3]
/**package.json**:12
`"main": "dist/index.js",`

I was wondering why the module is not recognised by my NodeJS application and I ascertained that your `/dist` folder is missing from the repo and so are the files in it (like `index.js`).

I was withal unable to find an `index.js` file anywhere in the repo.

**Comment by SamVerschueren** [comment]
The `dist` directory is missing from the repo because it's a TypeScript project. It builds the `dist` folder before publishing but the folder itself is not pushed to GitHub. When you install `map-age-cleaner`, you will notice that in your `node_modules`, the `dist` directory is present.

![image](https://user-images.githubusercontent.com/1913805/55214299-8fed2980-51f6-11e9-920e-3f2686b17667.png)

**Comment by zefirzdravkov** [comment]
It is because of my OS that I can not execute TypeScript files. Is there any way to download a pre-installed version from somewhere?

**Comment by SamVerschueren** [comment]
It's not a TypeScript file, it's a JavaScript file (`dist/index.js`). The `index.d.ts` is just a type definition file which helps you with Intellisense in editors like VS Code.
